services:
  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_DB: 
  #     POSTGRES_USER: 
  #     POSTGRES_PASSWORD: 

  nextjs-auth:
    build:
      context: ./
      dockerfile: nextjs.Dockerfile
    develop:
      watch:
        - action: sync+restart
          path: .
          target: /nextjs-auth
    # retart until db started
    restart: on-failure

  nginx:
    build:
      context: ./nginx
      dockerfile: nginx.Dockerfile
    restart: on-failure
    ports:
      - "8080:80"
      - "4430:443"
    # volumes:
    #   - ./nginx:/etc/nginx/ssl:ro
    depends_on:
      nextjs-auth:
        condition: service_started
